# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0801587fbc9be2830ebf13d83b9de5a17ac371276873bbf906eb3336dbd0a6b03b1ef4a213cdec75f16bd3e36f21483791a427cbdf765d658061f73e39ceed

test:
  secret_key_base: 347992093ba16cb9b6ace8094420fd16b81d0759695f49ad6ac141cb71092595fb4804338b859bdf6590a3283dbb16e3b43952b25560eda29e1f266acaf1586e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
